version: '3.8'

services:
  main-gateway:
    image: nginx:alpine
    container_name: main-api-gateway
    ports:
      - "81:81"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./confs:/etc/nginx/conf.d:ro
    networks:
      - main_net

networks:
  main_net:
    driver: bridge
    name: main_gateway_net
