events { worker_connections 1024; }
http {
    server {
        listen 80;
        location /catalog-api {
            proxy_pass http://zone3-catalog-api-envoy:8080;
            proxy_http_version 1.1;
        }
        location /orders-api {
            proxy_pass http://zone3-orders-api-envoy:8080;
            proxy_http_version 1.1;
        }
        location /payments-api {
            proxy_pass http://zone3-payments-api-envoy:8080;
            proxy_http_version 1.1;
        }
        location /auth-api {
            proxy_pass http://zone3-auth-api-envoy:8080;
            proxy_http_version 1.1;
        }
        resolver 127.0.0.11 valid=10s;
        set $main_gw main-api-gateway;
        location /_external/ {
            proxy_pass http://$main_gw:81/;
            proxy_http_version 1.1;
        }
    }
}
