apiVersion: 1

datasources:
  - name: Trino-HDFS
    type: trino-datasource
    uid: trino-hdfs-uid
    url: http://trino:8080
    access: proxy
    jsonData:
      user: admin
      catalog: hive
      schema: default
    editable: true

  - name: Redis-Zone1
    type: redis-datasource
    uid: redis-zone1-uid
    url: zone1-redis:6379
    access: proxy
    editable: true
